// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxrvdymrfbrmetcdaexv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cnZkeW1yZmJybWV0Y2RhZXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjA0NDUsImV4cCI6MjA2MjAzNjQ0NX0.IkUoinfi-UYMUlClYUgD-qQyLcx3a4uh3QQGlncOEVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);